spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/employeemgmtDev
    username: root
    password: root

---

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/employeemgmtProd
    username: root
    password: root

---

spring:
  profiles: test
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:employeemgmtTest
    username: test
    password: test
  h2:
    console:
      enabled: true
